### PR TITLE
refactor: Refactor homepage from ui design

### PR DESCRIPTION
**Pull request by aprilyang**

### CODE REVIEW

**Comment by Xuanwo** [comment]
How about fix https://github.com/beyondstorage/site/issues/132 in this PR?

**Comment by Xuanwo** [comment]
The link for matrix should be `https://matrix.to/#/#campfire:aos.dev`

**Comment by Xuanwo** [comment]
image

Can we remove this?

**Comment by aprilyang** [comment]
> #132

Fixed

**Review by Xuanwo — APPROVED** [review]

**Comment by Xuanwo** [comment]
> The link for matrix should be `https://matrix.to/#/#campfire:aos.dev`

Let's fix this in next PR!

**Pull request merged**
